apiVersion: v1
kind: Service
metadata:
  labels:
    app: anummers
  name: anummers-service
spec:
  ports:
  - nodePort: 30913
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: anummers
  type: NodePort
