apiVersion: v1
kind: Service
metadata:
  labels:
    app: persoonslijsten
  name: persoonslijsten-service
spec:
  ports:
  - nodePort: 31886
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: persoonslijsten
  type: NodePort
