apiVersion: v1
kind: Service
metadata:
  labels:
    app: bag
  name: bag-service
spec:
  ports:
  - nodePort: 30719
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bag
  type: NodePort
