# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push anummers
        id: docker_build_anummers
        uses: docker/build-push-action@v2
        with:
          context: ./anummers
          file: ./anummers/Dockerfile
          build-args: JAR_FILE=build/libs/anummers-0.0.1-SNAPSHOT.jar
          push: true
          tags: freerink/anummers:latest
          
      - name: Image digest anummers
        run: echo ${{ steps.docker_build_anummers.outputs.digest }}

      - name: Build and push persoonslijsten
        id: docker_build_persoonslijsten
        uses: docker/build-push-action@v2
        with:
          context: ./lo3pl
          file: ./lo3pl/Dockerfile
          build-args: JAR_FILE=build/libs/lo3pl-0.0.1-SNAPSHOT.jar
          push: true
          tags: freerink/persoonslijsten:latest
          
      - name: Image digest persoonslijsten
        run: echo ${{ steps.docker_build_persoonslijsten.outputs.digest }}
